version: '3.9'

services:
  favstickbot:
    image: favstickbot
    build:
      context: .
      target: prod
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo
    networks:
      - favstickbot
  mongo:
    image: mongo:7.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: '${MONGO_INITDB_DATABASE:-favstickbot}'
      MONGO_INITDB_USERNAME: $MONGO_INITDB_USERNAME
      MONGO_INITDB_PASSWORD: $MONGO_INITDB_PASSWORD
    restart: always
    networks:
      - favstickbot
    volumes:
      - mongo:/data/db
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

volumes:
  mongo:

networks:
  favstickbot:
