const ERROR_TYPES = require('./errorTypes');

module.exports = {
  DO_NOT_REPLY: [
    ERROR_TYPES.TELEGRAM.TOO_MANY_REQUESTS,
    ERROR_TYPES.TELEGRAM.USER_NOT_FOUND,
    ERROR_TYPES.TELEGRAM.CHAT_NOT_FOUND,
    ERROR_TYPES.TELEGRAM.BLOCKED_BY_USER,
    ERROR_TYPES.TELEGRAM.KICKED_FROM_GROUP,
    ERROR_TYPES.TELEGRAM.KICKED_FROM_SUPERGROUP,
    ERROR_TYPES.TELEGRAM.KICKED_FROM_CHANNEL,
    ERROR_TYPES.TELEGRAM.USER_DEACTIVATED,
    ERROR_TYPES.TELEGRAM.GROUP_DEACTIVATED,
    ERROR_TYPES.TELEGRAM.NOT_GROUP_MEMBER,
    ERROR_TYPES.TELEGRAM.NOT_SUPERGROUP_MEMBER,
    ERROR_TYPES.TELEGRAM.NOT_CHANNEL_MEMBER,
  ],
};
